spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME:booking}
    password: ${DB_PASSWORD:booking}
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - localhost:26379
          - localhost:26380
          - localhost:26381
